#!/usr/bin/env bash

DIR=${1:-`pwd`}
#PAGER="less"
PAGER="bat --paging=always"

# NOTE: the ls's -l and -F options are extremely expensive -- more than 10x slower...
# 	...this is relevant for very large numbers of files in a dir...
# NOTE: we are double quiting '\n' in -k View:... and -k DownDir:... as the 
# 	last '\' will be removed by lines and bash still needs an escaped '\n'
# XXX need to sanatize file names -- quotes will break things...
DIR="$DIR" \
PAGER="$PAGER" \
	go run lines \
		-l debug.log \
		-c 'echo ".." \
			ls --group-directories-first --dereference-command-line-symlink-to-dir "$DIR" ' \
		-t 'sed -e "s/$/%SPAN/"' \
		-p 'sed -e "s/%SPAN$//" \
			| xargs -i bash -c "\
				[ -d \"${DIR}/{}\" ] \
					&& printf -- \"{}/%%SPAN%8s\" \"<dir> \" \
					|| printf -- \"{}%%SPAN%8s\" \"\$(\
						ls -lh \"${DIR}/{}\" \
							| cut -d\" \" -f5 \
							| sed -e \"s/\\([0-9]$\\)/\\1 /\" \
					) \""' \
		-k UpDir:'
			DIR= realpath -s "$DIR/.."
			Update' \
		-k DownDir:'
			DIR= [ -d "${DIR}/${TEXT_LEFT%[*/=>@|]}" ] \\
				&& realpath -s "$DIR/${TEXT_LEFT%[*/=>@|]}" \\
				|| realpath -s "$DIR"
			Update' \
		-k View:'@ [ -d "${LEFT_TEXT%[*/=>@|]}" ] \\
				|| ${PAGER} "$DIR/${TEXT_LEFT%[*/=>@|]}"; \\
			true' \
		-k F3:'View' \
		-k Backspace2:'UpDir' \
		-k Backspace:'
			DIR= echo "/"
			Update' \
		-k Left:'UpDir' \
		-k Right:'DownDir' \
		-s 'DownDir' \
		--span="-8" \
		--span-separator="│" \
		--title ' $DIR %SPAN' \
		-b

