#!/usr/bin/bash

MSG=${1:-Are you sure?}

echo -e '%SPAN YES \n%SPAN NO ' \
	| ./lines \
		--title " $MSG %SPAN" \
		--size 20,4 \
		--status "%SPAN" \
		-s '> [ "${TEXT/\%SPAN /}" == "YES " ] \n Exit' \
		-r 'Fail' \
		--key y:'Exit' \
		--key n:'Fail' \
		--border
